app:
  name: nginx
  image: us-central1-docker.pkg.dev/stm-01/my-app-repo/html-nginx-app
  versionBlue: v1           # Label for blue
  versionGreen: v2          # Label for green
  activeVersion: v1         # This is used in the Service selector
  replicas: 2
  tlsSecret: profit-tls
  ingressHost: nginx.profitokrs.com
  staticIpName: nginx-ingress-staticip
  sslPolicy: nginx-ssl-security

