apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  namespace: {{ .Release.Namespace }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/load-balancer-type: "Internal"
spec:
  selector:
    app: {{ .Values.app.name }}
    version: {{ .Values.app.activeVersion }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

