apiVersion: v1
kind: Service
metadata:
  name: nginx-service-blue
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx
    color: blue
    enabled: "true"
  annotations:
{{- range $key, $value := .Values.services.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  selector:
    app: nginx
    color: blue
  ports:
    - protocol: TCP
      port: {{ .Values.services.port }}
      targetPort: {{ .Values.services.targetPort }}
  type: {{ .Values.services.type }}

