apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-app-blue
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx
    color: blue
spec:
  serviceName: nginx-app-headless
  replicas: {{ .Values.statefulsets.replicas }}
  selector:
    matchLabels:
      app: nginx
      color: blue
  template:
    metadata:
      labels:
        app: nginx
        color: blue
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: nginx-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.statefulsets.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.statefulsets.storage }}

