apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: 80
      targetPort: 80

