apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.app.name }}-green
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
    version: {{ .Values.app.versionGreen }}
spec:
  serviceName: {{ .Values.app.name }}-headless
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      version: {{ .Values.app.versionGreen }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        version: {{ .Values.app.versionGreen }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.app.image }}:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: nginx-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi

